# https://docs.github.com/en/actions/guides/publishing-docker-images
name: Publish Docker image
on:
  release:
    types: [published]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  push_to_registries:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set output
        id: vars
        run: |
          ref=${GITHUB_REF#*:}
          echo ::set-output name=tag::${ref#*_}
          echo ::set-output name=coin::${ref%%_*}
  
      - run: echo "$GITHUB_CONTEXT"
      - run: echo "$tag"
      - run: echo "$coin"
        
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
        
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
        
#      - name: Log into Docker Hub
#        uses: docker/login-action@v1 
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
          
#      - name: Push to Docker Hub
#        id: docker_build
#        uses: docker/build-push-action@v2.4.0
#        with:
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: cinderblockgames/${{ steps.vars.outputs.coin }}-public-api:${{ steps.vars.outputs.tag }}
          
#      - name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}
